void setStrokeMM(int strokeReq)
void setStrokePerc(float strokePercentage)
void motorStop()
void motorForward(int PWM_val)
void doEncoderB()
void doEncoderA()
void robot_setup()
boolean validatePacket(unsigned int packetSize, byte *packet)
boolean sendPacket(unsigned int payloadSize, byte *payload)
